site_name: USTL-ACM算法合集
site_url: https://github.com/Risingrode/USTL_ACM
site_author: ACM校队

repo_name: USTL-ACM算法合集
repo_url: https://github.com/Risingrode/USTL_ACM


edit_uri: blob/master/docs/

# 主题设置
theme:
  name: material
  language: zh
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=nav#navigation-tabs
    - navigation.tabs
    - navigation.tabs.sticky
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=footer
    - navigation.footer
    - navigation.top
    - navigation.sections
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=edit#code-actions
    - content.action.edit
    - content.tabs.link
    - content.code.copy


# 版权
copyright: 版权声明：USTL-ACM专属

# 插件
plugins:
  - awesome-pages:
      strict: false
  # - i18n:
  #     default_language: zh
  #     material_alternate: true
  #     languages:
  #       zh:
  #         name: 简体中文
  #         build: true
#      nav_translations:
#        # 格式是： 中文替换名 + 文件夹名字
#        首页 : Home
#        Markdown规范 : Markdown
  - search:
      lang: en





# 这里是导航栏配置，写完一个文档后要加到这里，注意空格，注意冒号的中英文，注意缩进
nav:
  # 格式是： 中文替换名 + 文件夹名字
  - 首页 :
    - 前言: index.md
    - Windows配置: Home/Windows_Setup.md
  - Markdown规范 :
    - Markdown: Markdown/markdown.md
    - Latex: Markdown/latex.md
  - 基础算法:
    - 二分算法: Algo1/二分算法.md
    - 贪心算法: Algo1/贪心算法.md
    - 前缀和: Algo1/前缀和.md
    - 双指针: Algo1/双指针.md
    - 位运算: Algo1/位运算.md
    - 排序算法: Algo1/排序算法.md
    - 背包: Algo1/背包.md
    - DFS: Algo1/DFS.md
    - BFS: Algo1/BFS.md
    - Notice: Algo1/Notice.md
    - Other: Algo1/其他算法.md
  - 算法模板:
      - 基础算法模板: 知识点/基础算法模板.md
  - 语言:
    - C++: Language/C++.md
    - Python: Language/Python.md
    - Java: Language/Java.md
  - 刷题:
    - LeetCode: Problem/LeetCode.md













# LaTeX支持
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.highlight:
      use_pygments: true
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js






